//////////////////////////////////////////////////////////////////////////////////////////////////
//
// 파일이름: book.cpp
//
// 내용: 책 모음
//
//////////////////////////////////////////////////////////////////////////////////////////////////

#include "book.h"
#include "skill_use.h"

book_infor static_book_list[BOOK_LAST]=
{
	book_infor(LOC_SYSTEM_ITEM_BOOK_FIRE_BASE,BOOK_FIRE_BASE,300,SPL_BURN,SPL_FLAME,SPL_FIRE_WALL,SPL_FIRE_BALL,SPL_FIRE_BOLT,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_COLD_BASE,BOOK_COLD_BASE,300,SPL_FROZEN,SPL_FROST,SPL_FREEZE,SPL_ICE_CLOUD,SPL_ICE_BOLT,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_POISON_BASE,BOOK_POISON_BASE,300,SPL_STING,SPL_CURE_POISON,SPL_POISON_SKIN,SPL_CONFUSE_CLOUD,SPL_VENOM_BOLT,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_WIZARD_BASE,BOOK_WIZARD_BASE,300,SPL_MAGIC_TANMAC,SPL_BLINK,SPL_DIAMOND_HARDNESS,SPL_SUMMON_OPTION,SPL_CONFUSE_CLOUD,SPL_FIRE_WALL,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_EARTH_BASE,BOOK_EARTH_BASE,30,SPL_STONE_PUNCH,SPL_STONE_ARROW,SPL_STONE_TRAP,SPL_STONE_UPLIFT,SPL_KANAME_DRILL,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_AIR_BASE,BOOK_AIR_BASE,300,SPL_SHOCK,SPL_LEVITATION, SPL_TWIST,SPL_DISCHARGE,SPL_THUNDER,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_SUMMON_BASE,BOOK_SUMMON_BASE,300,SPL_SUMMON_MOOK,SPL_SUMMON_OPTION,SPL_SUMMON_BIRD,SPL_SUMMON_GOLEM,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_ALCHMIST_BASE,BOOK_ALCHMIST_BASE,300,SPL_STONE_PUNCH,SPL_DIAMOND_HARDNESS,SPL_POISON_SKIN,SPL_SUMMON_GOLEM,SPL_EMERALD_CITY,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_PSYCHOLOGIST_BASE,BOOK_PSYCHOLOGIST_BASE,300,SPL_HYPNOSIS, SPL_MIND_BENDING, SPL_MUTE, SPL_SELF_INJURY, SPL_CHARM,SPL_NONE ,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_BRAND_BASE,BOOK_BRAND_BASE,400,SPL_VEILING,SPL_DIAMOND_HARDNESS,SPL_POISON_SKIN,SPL_SILENCE,SPL_HASTE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_MAID_BASE,BOOK_MAID_BASE,400,SPL_BLINK,SPL_SUMMON_OPTION,SPL_KNIFE_COLLECT,SPL_TIME_PARADOX,SPL_PRIVATE_SQ,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_SHOCK,BOOK_SHOCK,500,SPL_SHOCK,SPL_LEVITATION,SPL_DISCHARGE,SPL_THUNDER,SPL_CHAIN_LIGHTNING,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_PRACTICE,BOOK_PRACTICE,450,SPL_BURN,SPL_FROZEN,SPL_VEILING,SPL_STONE_PUNCH,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_SUB,BOOK_SUB,450,SPL_DRAW_POWER,SPL_DIAMOND_HARDNESS,SPL_BLINK,SPL_MIND_BENDING,SPL_SUMMON_BIRD,SPL_STONE_TRAP,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_STALKING,BOOK_STALKING,600,SPL_STING,SPL_CONFUSE,SPL_CONFUSE_CLOUD,SPL_INVISIBLE,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_CLOUD,BOOK_CLOUD,700,SPL_TWIST,SPL_FIRE_WALL,SPL_CONFUSE_CLOUD,SPL_POISON_CLOUD,SPL_ICE_CLOUD,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_CONJURE,BOOK_CONJURE,700,SPL_MAGIC_TANMAC,SPL_SUMMON_OPTION,SPL_LASER,SPL_FIRE_BOLT,SPL_ICE_BOLT,SPL_SUMMON_ELEC_BALL,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_HEX,BOOK_HEX,400,SPL_GLOW,SPL_MUTE,SPL_CONFUSE,SPL_CHARM,SPL_SILENCE,SPL_INVISIBLE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_DEFENSE,BOOK_DEFENSE,600,SPL_VEILING,SPL_DIAMOND_HARDNESS,SPL_CURE_POISON,SPL_DISCHARGE,SPL_SILENCE,SPL_FIELD_VIOLET,SPL_NONE,SPL_NONE),	
	book_infor(LOC_SYSTEM_ITEM_BOOK_ENCHANT,BOOK_ENCHANT,700,SPL_AIR_STRIKE,SPL_FREEZE,SPL_STONE_UPLIFT,SPL_FIRE_BALL,SPL_HASTE,SPL_SUMMON_UFO,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_TRANSITION,BOOK_TRANSITION,500,SPL_DRAW_POWER,SPL_BLINK,SPL_TELEPORT_OTHER,SPL_TELEPORT_SELF,SPL_RECALL,SPL_KNIFE_COLLECT,SPL_NONE,SPL_NONE),	
	book_infor(LOC_SYSTEM_ITEM_BOOK_TENSI,BOOK_TENSI,1000,SPL_STONE_UPLIFT,SPL_KANAME_DRILL,SPL_STONE_FORM,SPL_SUMMON_NAMAZ,SPL_SHATTER,SPL_NONE,SPL_NONE,SPL_NONE),	
	book_infor(LOC_SYSTEM_ITEM_BOOK_TEST_ANNIHILATE,BOOK_TEST_ANNIHILATE,1500,SPL_LUMINUS_STRIKE,SPL_SPARK,SPL_FIRE_STORM,SPL_PERFERT_FREEZE,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_DEBUF,BOOK_DEBUF,1500,SPL_ANIMAL_CHANGE,SPL_PRIVATE_SQ,SPL_INVISIBLE,SPL_FIELD_VIOLET,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_MAID_ULTI,BOOK_MAID_ULTI,1500,SPL_PRIVATE_SQ,SPL_CONTROLED_BLINK,SPL_THE_WORLD,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_ICE_ULTI,BOOK_ICE_ULTI,1500,SPL_ICE_BOLT,SPL_ICE_CLOUD,SPL_BLIZZARD,SPL_PERFERT_FREEZE,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_SUMMON_ULTI,BOOK_SUMMON_ULTI,1500,SPL_SUMMON_UFO,SPL_SUMMON_YOUKAI,SPL_SUMMON_NAMAZ,SPL_DOLLS_WAR,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_AIR_ULTI,BOOK_AIR_ULTI,1500,SPL_VEILING,SPL_TWIST,SPL_AIR_STRIKE,SPL_MACRO_BURST,SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_ALCHMY_ULTI,BOOK_ALCHMY_ULTI,1500,SPL_EMERALD_CITY,SPL_STONE_FORM,SPL_AUTUMN_BLADE,SPL_PHILOSOPHERS_STONE, SPL_NONE,SPL_NONE,SPL_NONE,SPL_NONE),
	book_infor(LOC_SYSTEM_ITEM_BOOK_LIGHT_BASE,BOOK_LIGHT_BASE,300,SPL_MAGIC_TANMAC,SPL_SUMMON_OPTION,SPL_HOMING_TANMAC,SPL_LASER,SPL_ALLROUND_TANMAC,SPL_NONE,SPL_NONE,SPL_NONE)
};

LOCALIZATION_ENUM_KEY random_book_list[RANDOM_BOOK_NUM]=
{
	LOC_SYSTEM_ITEM_BOOK_RANDOM1,
	LOC_SYSTEM_ITEM_BOOK_RANDOM2,
	LOC_SYSTEM_ITEM_BOOK_RANDOM3,
	LOC_SYSTEM_ITEM_BOOK_RANDOM4,
	LOC_SYSTEM_ITEM_BOOK_RANDOM5,
	LOC_SYSTEM_ITEM_BOOK_RANDOM6,
	LOC_SYSTEM_ITEM_BOOK_RANDOM7
};





string GetBookInfor(book_list book_)
{
	switch(book_)
	{
	default:
	case BOOK_CUSTOM_BOOK:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_CUSTOM);
	case BOOK_FIRE_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_FIRE_BASE);
	case BOOK_COLD_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_COLD_BASE);
	case BOOK_POISON_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_POISON_BASE);
	case BOOK_WIZARD_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_WIZARD_BASE);
	case BOOK_EARTH_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_EARTH_BASE);
	case BOOK_AIR_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_AIR_BASE);
	case BOOK_SUMMON_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_SUMMON_BASE);
	case BOOK_ALCHMIST_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_ALCHMIST_BASE);
	case BOOK_PSYCHOLOGIST_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_PSYCHOLOGIST_BASE);
	case BOOK_BRAND_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_BRAND_BASE);
	case BOOK_MAID_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_MAID_BASE);
	case BOOK_SHOCK:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_SHOCK);
	case BOOK_PRACTICE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_PRACTICE);
	case BOOK_SUB:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_SUB);
	case BOOK_STALKING:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_STALKING);
	case BOOK_CLOUD:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_CLOUD);
	case BOOK_CONJURE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_CONJURE);
	case BOOK_HEX:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_HEX);
	case BOOK_DEFENSE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_DEFENSE);
	case BOOK_ENCHANT:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_ENCHANT);
	case BOOK_TRANSITION:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_TRANSITION);
	case BOOK_TENSI:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_TENSI);
	case BOOK_TEST_ANNIHILATE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_TEST_ANNIHILATE);
	case BOOK_DEBUF:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_DEBUF);
	case BOOK_MAID_ULTI:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_MAID_ULTI);
	case BOOK_ICE_ULTI:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_ICE_ULTI);
	case BOOK_SUMMON_ULTI:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_SUMMON_ULTI);
	case BOOK_AIR_ULTI:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_AIR_ULTI);
	case BOOK_ALCHMY_ULTI:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_ALCHMY_ULTI);
	case BOOK_LIGHT_BASE:
		return LocalzationManager::locString(LOC_SYSTEM_ITEM_DESCRIPTION_BOOK_LIGHT_BASE);
	}
}


bool isRareBook(book_list book_) {
	switch(book_)
	{
	case BOOK_TENSI:
	case BOOK_TEST_ANNIHILATE:
	case BOOK_DEBUF:
	case BOOK_MAID_ULTI:
	case BOOK_ICE_ULTI:
	case BOOK_SUMMON_ULTI:
	case BOOK_AIR_ULTI:
	case BOOK_ALCHMY_ULTI:
		return true;		
	default:
		return false;
	}
}


book_list SchoolToBook(skill_type skill_)
{
	switch(skill_)
	{
	case SKT_ALCHEMY:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_BRAND_BASE,10);
			list_.push(BOOK_SUB,10);
			list_.push(BOOK_DEFENSE,10);
			list_.push(BOOK_ENCHANT,2);
			list_.push(BOOK_ALCHMIST_BASE,10);
			list_.push(BOOK_ALCHMY_ULTI,5);			
			return list_.pop();
		}
	case SKT_MENTAL:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_STALKING,10);
			list_.push(BOOK_HEX,10);
			list_.push(BOOK_PSYCHOLOGIST_BASE,10);
			list_.push(BOOK_DEBUF,3);
			return list_.pop();
		}
	case SKT_CONJURE:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_FIRE_BASE,8);
			list_.push(BOOK_COLD_BASE,8);
			list_.push(BOOK_CLOUD,8);
			list_.push(BOOK_SHOCK,7);
			list_.push(BOOK_LIGHT_BASE,10);
			list_.push(BOOK_TEST_ANNIHILATE,2);
			return list_.pop();
		}
	case SKT_FIRE:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_FIRE_BASE,10);
			list_.push(BOOK_ENCHANT,2);
			return list_.pop();
		}
	case SKT_COLD:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_COLD_BASE,10);
			list_.push(BOOK_ICE_ULTI,3);
			list_.push(BOOK_ENCHANT,2);
			return list_.pop();
		}
	case SKT_EARTH:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_EARTH_BASE,10);
			list_.push(BOOK_TENSI,3);
			list_.push(BOOK_ENCHANT,2);
			return list_.pop();			
		}
	case SKT_AIR:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_AIR_BASE,10);
			list_.push(BOOK_DEFENSE,10);
			list_.push(BOOK_CLOUD,10);
			list_.push(BOOK_ENCHANT,2);
			list_.push(BOOK_AIR_ULTI,5);
			
			return list_.pop();
		}
	case SKT_SUMMON:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_SUMMON_BASE,10);
			list_.push(BOOK_ENCHANT,2);
			list_.push(BOOK_SUMMON_ULTI,3);
			return list_.pop();
		}
	case SKT_TRANS:
		{
			random_extraction<book_list> list_;
			list_.push(BOOK_TRANSITION,10);
			list_.push(BOOK_MAID_ULTI,3);
			return list_.pop();
		}
	default:
		{
			return (book_list)randA(BOOK_LAST-1);
		}
	}
} 
